Functions
wildkain/Thinknetica_modern_JS pull request #3
Opened 2022-07-16 12:45 UTC by wildkain

2022-07-16 17:44 UTC, PonomareVlad requested changes
Нужно исправить решение **4-й** задачи + опционально доработать решения для задач **2** и **3**

2022-07-16 17:44 UTC, PonomareVlad commented on Lesson_3/task_2.js
> +const calculate = cache();
Тут что-то не так 🙂

```js
console.log(calculate(3, 3)); // {value: 27, fromCache: false}
console.log(calculate(3, 3)); // {value: 27, fromCache: true}
console.log(calculate(3, 2)); // {value: 9, fromCache: false}
console.log(calculate(3, 3)); // {value: 27, fromCache: false}
```

2022-07-16 17:44 UTC, PonomareVlad commented on Lesson_3/task_3.js
> +        history.push({operation: operation, operands: operands})
При объявлении объекта можно использовать сокращенный формат передачи свойств
```suggestion
        history.push({operation, operands})
```

2022-07-16 17:44 UTC, PonomareVlad commented on Lesson_3/task_3.js
> +        operand_2 = full_operations[2];
Не забывайте про возможность деструктуризации массива:
```suggestion
        [operand_1, operation, operand_2] = full_operations;
```

2022-07-16 17:44 UTC, PonomareVlad commented on Lesson_3/task_3.js
> +        return console.log(operations[operation](Number(operand_1), Number(operand_2)));
Приведение к типу `Number` лучше перенести в момент установки значения переменных, а не в момент их использования

2022-07-16 17:44 UTC, PonomareVlad commented on Lesson_3/task_3.js
> +        return console.log(operations[operation](Number(operand_1), Number(operand_2)));
Также обратите внимание, что сейчас при вызове `calculator.operation()` результат вычисления не возвращается а только выводится в консоль

2022-07-16 17:44 UTC, PonomareVlad commented on Lesson_3/task_4.js
> +    }
> ... возвращаем случайный **_шестизначный_** ID билета, создать ID можно любым способом

Проверьте длину ваших идентификаторов:

```js
const generateId = function () {
    return (Math.random() + 1).toString(36).substring(6)
}

const test = Array(100).fill().map(() => generateId().length)

console.debug('ID length', {min: Math.min(...test), max: Math.max(...test)})
```

2022-07-16 17:44 UTC, PonomareVlad commented on Lesson_3/task_4.js
> +        let event = events.find(e => e['event_name'] === event_name)
Эффективнее будет использовать объект (поиск по ключам) вместо массива, т.к. перебор всех значений через `Array.find()` может затянуться

2022-07-16 17:44 UTC, PonomareVlad commented on Lesson_3/task_4.js
> +    }
Нет проверки наличия данных о мероприятии

2022-07-16 17:44 UTC, PonomareVlad commented on Lesson_3/task_4.js
> +    }
Также опционально можете добавить проверку на дублирующиеся идентификаторы

2022-07-16 17:44 UTC, PonomareVlad commented on Lesson_3/task_4.js
> +        let ticket = sold_tickets.find(s_ticket => s_ticket.id === ticket_id)
Тут также будет эффективнее использовать поиск по ключам объекта, вместо массива

2022-07-16 17:44 UTC, PonomareVlad commented on Lesson_3/task_4.js
> +    }
И проверять наличие удаляемого билета, перед расчетом кассы

2022-07-16 17:44 UTC, PonomareVlad commented on Lesson_3/task_4.js
> +        sold_tickets = sold_tickets - [ticket]
А на этой строке, в переменную `sold_tickets` будет установлено значение `NaN` т.к. оператор `-` не умеет вычитать массивы

2022-07-17 10:36 UTC, wildkain commented on Lesson_3/task_2.js
> +const calculate = cache();
пофиксил

2022-07-17 10:37 UTC, wildkain commented on Lesson_3/task_4.js
> +    }
добавил проверку, изменил функцию генерации id

2022-07-17 10:46 UTC, wildkain commented on Lesson_3/task_4.js
> +        let event = events.find(e => e['event_name'] === event_name)
Насколько вообще логично  для хранения коллекции использовать не массив? 
вы предлагаете нечто в таком роде
```javascript
let events = { 'event_name':  event_details_obj }
let event  = events[event_name]
```

насколько я понял. 
Это предполагает что эвент можно будет идентифицировать **только** по названию. 
Если нам будет необходимо находить эвент например по названию и дате проведения  - то поиск по ключу в обьекте не подойдет уже (((

2022-07-17 20:22 UTC, PonomareVlad commented on Lesson_3/task_4.js
> +        let event = events.find(e => e['event_name'] === event_name)
Да, при таких условиях, для поиска одновременно по дате и названию придется перебирать как массив так и объект (коллекцию)

Однако это уже совсем другая история, т.к. её можно будет оптимизировать другим способом, например создав дополнительный массив для индексации мероприятий по дате:

```js
const events = {"event_id": {name: 'event_name'}} // Информация о мероприятиях доступная по ключу

const eventsByTimestamp = [] // Ключи мероприятий упорядоченные по дате (временной метке Unix)

eventsByTimestamp[1658088299] = ["event_id", "parallel_event_id"] // Мероприятия в одно время

const findEvents = (name, from, to) => // Поиск мероприятий по названию и дате
    eventsByTimestamp.slice(from, to).flat().map(id => events[id]).filter(e => e.name === name)
```

2022-07-17 21:37 UTC, PonomareVlad requested changes
Нужно доработать решения для задач **3** и **4**

2022-07-17 21:37 UTC, PonomareVlad commented on Lesson_3/task_2.js
> +        }
Отмечу, что с каждой операцией, в которой будет повторятся первый операнд, время на поиск кэшированных расчетов через `Array.find()` будет линейно расти

Рекомендую использовать либо вложенные массивы/объекты (`cache[x][y] = result`) либо составные ключи в объекте (`cache[x + '_' + y] = result`)

2022-07-17 21:37 UTC, PonomareVlad commented on Lesson_3/task_3.js
> +        full_operations = operation_string.split(' ').map(o => parseInt(o) ? parseInt(o) : o );
Обратите внимание на то, как ваша функция обрабатывает нули:

```js
const operand = "0"

const test = parseInt(operand) ? parseInt(operand) : operand

console.debug(typeof test) // string
```

2022-07-17 21:37 UTC, PonomareVlad commented on Lesson_3/task_4.js
> +            return generatedID();
Также, обратите внимание, что при повторном вызове функции `generatedID()` может вернуться другое значение, и проверка на дубликаты не будет работать корректно

2022-07-17 21:37 UTC, PonomareVlad commented on Lesson_3/task_4.js
> +            return  generateId();
Лучше избегать рекурсивного вызова функций (т.к. [стек вызовов ограничен](https://stackoverflow.com/questions/7826992/browser-javascript-stack-size-limit)), и вместо этого использовать циклы, например:

```js
let id;

do {id = generatedID()} while (sold_tickets.map(t => t.id).includes(id))
```

2022-07-17 21:37 UTC, PonomareVlad commented on Lesson_3/task_4.js
> +            return  generateId();
И еще лучше, заменить перебор массива проданных билетов `sold_tickets.map(t => t.id)` на поиск по ключу `sold_tickets[id]`

2022-07-17 21:37 UTC, PonomareVlad commented on Lesson_3/task_4.js
>      }
Похоже, нет никакой необходимости размещать код покупки билета во вложенной функции, т.к. вы в любом случае возвращаете результат её выполнения без дополнительных условий:

```js
const buyTicket = (event_name) => {
    let event = events.find(e => e['event_name'] === event_name)
    if (event) {
        cashier += event.ticket_price
        let ticketObj = { id: generateId(), event_name: event.event_name, cost: event.ticket_price}
        sold_tickets.push(ticketObj)
        return ticketObj
    } else {
        return console.log('Event not found')
    }
}
```

2022-07-17 21:37 UTC, PonomareVlad commented on Lesson_3/task_4.js
> +            sold_tickets = sold_tickets.filter(t => ![ticket].includes(t))
Т.к. вы используете [`Array.find()`](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Array/find) для поиска билета, то можно удалить элемент из массива более эффективным способом, запомнив его индекс:

```js
let index;

let ticket = sold_tickets.find((s_ticket, i) => {
    const result = s_ticket.id === ticket_id;
    if (result) index = i;
    return result;
});

delete sold_tickets[index];
```

2022-07-18 17:34 UTC, PonomareVlad approved these changes
Все решения приняты 🎉

2022-07-18 17:34 UTC, PonomareVlad commented on Lesson_3/task_3.js
> +        full_operations = operation_string.split(' ').map(o => o == 0 ? 0 :  (parseInt(o) || o ));
Не забывайте про поддержку дробных чисел:

```suggestion
        full_operations = operation_string.split(' ').map(o => isNaN(o) ? o : parseFloat(o));
```

2022-07-18 17:34 UTC, PonomareVlad commented on Lesson_3/task_4.js
>          return ticket();
Предлагаю освободить немного памяти и улучшить читабельность кода, путем устранения вложенной функции:

```suggestion
            if (event) {
                cashier += event.ticket_price
                let ticketObj = {id: generateId(), event_name: event.name, cost: event.ticket_price}

                sold_tickets[ticketObj.id] = ticketObj
                return ticketObj
            } else {
                return console.log('Event not found')
            }
```

2022-07-18 17:55 UTC, merged