ships and shipyards
wildkain/Thinknetica_modern_JS pull request #5
Opened 2022-07-21 14:41 UTC by wildkain

2022-07-21 15:49 UTC, PonomareVlad requested changes
Нужно исправить решение задачи

2022-07-21 15:49 UTC, PonomareVlad commented on Lesson_4/task_4.js
> +        ship.type === this.ship_attrs.type ? console.log("Repairing ship...") : console.log('Error: [Wrong ship type]')
> Проверка типа корабля должна осуществляться путем сравнения прототипа.

2022-07-21 16:20 UTC, wildkain commented on Lesson_4/task_4.js
> +        if (Object.getPrototypeOf(ship) == Object.getPrototypeOf(this.buildShip(ship))) {
не могу понять почему возвращается false

c виду вполне одинаковые прототипы

<img width="615" alt="Screenshot 2022-07-21 at 19 18 04" src="https://user-images.githubusercontent.com/15811438/180264196-5ed08906-acd7-49cc-a5af-48e161cf23c7.png">

2022-07-21 16:27 UTC, PonomareVlad commented on Lesson_4/task_4.js
> +        if (Object.getPrototypeOf(ship) == Object.getPrototypeOf(this.buildShip(ship))) {
Потому что вы проверяете не конструктор прототипа, а экземпляр:

```js
Object.setPrototypeOf(this, new Ship(attrs)) // экземпляр new Ship()
```

2022-07-21 16:39 UTC, wildkain commented on Lesson_4/task_4.js
> +        if (Object.getPrototypeOf(ship) == Object.getPrototypeOf(this.buildShip(ship))) {
какое-то нелогичное сравнение((( 
есть обьект ship  с прототипом  EngineShip
есть вновь созданный обьект через функцию buildShip(), через туже функцию и с теми же параметрами через которую был создан обьект ship

и при этом их прототипы неравны 🤯

2022-07-21 17:13 UTC, wildkain commented on Lesson_4/task_4.js
> +        if (Object.getPrototypeOf(ship) == Object.getPrototypeOf(this.buildShip(ship))) {
как тогда можно сравнивать прототипы обьектов, если их прототипы  это разные экземпляры

а setPrototypeOf ничего кроме обьектов-экземпляров не принимает

2022-07-21 20:14 UTC, PonomareVlad commented on Lesson_4/task_4.js
> +        if (Object.getPrototypeOf(ship) == Object.getPrototypeOf(this.buildShip(ship))) {
Давайте рассмотрим по шагам:

```js
const ship = new EngineShipyard().buildShip() // Создаем верфь и запрашиваем создание корабля

// this.buildShip = function () { // В функции создания корабля...
return new EngineShip() // ...вызывается его конструктор

// const EngineShip = function () { // В конструкторе корабля...
Object.setPrototypeOf(this, new Ship())  // ...прототипом устанавливается экземпляр new Ship

// Проверяем прототип корабля
console.debug(Object.getPrototypeOf(ship)) // Ship {type: 'EngineShip'} вместо EngineShip
```

На этом моменте мы видим первую ошибку — прототипом корабля является класс Ship вместо EngineShip

2022-07-21 20:17 UTC, PonomareVlad commented on Lesson_4/task_4.js
> +        if (Object.getPrototypeOf(ship) == Object.getPrototypeOf(this.buildShip(ship))) {
Теперь проверим, почему сравнение прототипа корабля возвращает `false` для одинаковых экземпляров:

```js
// т.к. прототипом кораблей устанавливаются экземпляры new Ship, то попробуем сравнить их напрямую:
console.debug(new Ship({}) == new Ship({})) // false т.к. это два разных обьекта

// а теперь сравним прототипы этих экземпляров:
console.debug(Object.getPrototypeOf(new Ship({})) == Object.getPrototypeOf(new Ship({}))) // true

// соответственно, чтобы сравнить прототипы кораблей одинакового типа, используем такое условие:
const ship_1 = new EngineShipyard().buildShip()
const ship_2 = new EngineShipyard().buildShip()

console.debug(
    Object.getPrototypeOf(Object.getPrototypeOf(ship_1))
    ===
    Object.getPrototypeOf(Object.getPrototypeOf(ship_2))
) // true
```

Обратите внимание, что это условие сработает только в текущей версии кода, и после того как вы исправите предыдущую ошибку, его можно будет сильно упростить

2022-07-22 08:06 UTC, wildkain commented on Lesson_4/task_4.js
> +        if (Object.getPrototypeOf(ship) == Object.getPrototypeOf(this.buildShip(ship))) {
> соответственно, чтобы сравнить прототипы кораблей, используем такое условие:
 но вот тут же сравниваются прототипы прототипов 
 они равны, ок - но это никак не поможет в условии проверки, потому что - 
 если мы изменим 1 верфь на парусную  - сравнение прототипов прототипов также будет возвращать `true`
 
 ```
 const ship_1 = new EngineShipyard().buildShip()
 const ship_2 = new SailingShipyard().buildShip()

console.debug(
    Object.getPrototypeOf(Object.getPrototypeOf(ship_1)) // Object.getPrototypeOf(new Ship({})
    ==
    Object.getPrototypeOf(Object.getPrototypeOf(ship_2)) // Object.getPrototypeOf(new Ship({})
) // true

2022-07-22 08:14 UTC, PonomareVlad commented on Lesson_4/task_4.js
> +        if (Object.getPrototypeOf(ship) == Object.getPrototypeOf(this.buildShip(ship))) {
Все верно, по этому сначала нужно решить проблему с тем, что у вас в прототипах кораблей устанавливается `Ship` вместо `EngineShip` и `SailShip`

2022-07-22 09:13 UTC, wildkain commented on Lesson_4/task_4.js
> +        if (Object.getPrototypeOf(ship) == Object.getPrototypeOf(this.buildShip(ship))) {
хотя вобщем-то все решилось удалением Ship

2022-07-22 10:12 UTC, PonomareVlad commented on Lesson_4/task_4.js
> +        if (Object.getPrototypeOf(ship) == Object.getPrototypeOf(this.buildShip(ship))) {
Неплохо, а теперь попробуйте обойтись без создания временного корабля при сравнении типов 🙂

```js
this.buildShip(ship) // Без этого
```

2022-07-22 10:35 UTC, wildkain commented on Lesson_4/task_4.js
> +        if (Object.getPrototypeOf(ship) == Object.getPrototypeOf(this.buildShip(ship))) {
сложное((( 
у нас есть входящий объект, прототип которого нам нужно сравнить с каким-то другим прототипом.
 в данном случае с прототипом объекта, которые выпускает текущая верфь. 
 как мы узнаем какие объекты выпускает верфь? выпустим новый корабль и узнаем его прототип
 
 Но, если мы НЕ создадим новый корабль, у нас не будет объекта с прототипом которого можно сравнивать прототип "входящего" корабля.

2022-07-22 10:43 UTC, wildkain commented on Lesson_4/task_4.js
> +        if (Object.getPrototypeOf(ship) == Object.getPrototypeOf(this.buildShip(ship))) {
ну только если заменить 
```javascript
Object.getPrototypeOf(ship) == Object.getPrototypeOf(this.buildShip(ship))
```


```javascript
Object.getPrototypeOf(ship) == Object.getPrototypeOf(new this.ship_attrs.type((ship)))
```

но это тоже самое по сути - создается новый объект и у него проверяется прототип

2022-07-22 11:22 UTC, PonomareVlad commented on Lesson_4/task_4.js
> +        if (Object.getPrototypeOf(ship) == Object.getPrototypeOf(this.buildShip(ship))) {
[Подсказка](https://github.com/PonomareVlad/Thinknetica/blob/102939d8571ef71624f32765e7142d9514e71068/4/2.mjs#L7)

2022-07-24 11:09 UTC, wildkain commented on Lesson_4/task_4.js
> +        if (Object.getPrototypeOf(ship) == Object.getPrototypeOf(this.buildShip(ship))) {
спасибо за подсказку, попробовал применить)

2022-07-25 19:31 UTC, PonomareVlad approved these changes
Отлично 👍🏻

2022-07-25 19:31 UTC, PonomareVlad commented on Lesson_4/task_4.js
> +}
Можно еще немного сократить класс верфи и хранить ссылку на класс корабля только в одном месте:

```suggestion
const EngineShipyard = function () {
    Object.setPrototypeOf(this, new commonShipyard())
    Object.assign(this, {
        shipType: EngineShip,
        buildShip: function ({engine_power, material} = {}) {
            return new this.shipType({engine_power, material})
        }
    })
}
```

2022-07-27 17:30 UTC, merged

2022-07-27 18:00 UTC, PonomareVlad reviewed
Если что, класс второй верфи можно упростить тем же способом, а то как-то несимметрично получается 🙂