Events
wildkain/Thinknetica_modern_JS pull request #8
Opened 2022-08-07 12:41 UTC by wildkain

2022-08-08 18:37 UTC, PonomareVlad requested changes

2022-08-08 18:37 UTC, PonomareVlad commented on Lesson_7/main.js
> +})
> Должна поддерживаться следующая функциональность:
> ...
> 4. Добавлять свои нестандартные операции и отображать кнопки для этих операций на экранe

2022-08-08 18:51 UTC, wildkain commented on Lesson_7/main.js
> +})
Вот этот пункт совсем не понял, сорри
Что значит возможность добавлять функциональность? В каком виде? Какой интерфейс? Непонятное(

2022-08-09 15:06 UTC, PonomareVlad commented on Lesson_7/main.js
> +})
Полагаю, что это можно реализовать используя форму с двумя полями: для ввода идентификатора операции и кода для функции

2022-08-14 13:16 UTC, wildkain commented on Lesson_7/main.js
> +})
добавил

2022-08-16 08:41 UTC, PonomareVlad approved these changes

2022-08-23 19:25 UTC, merged